[project]
name = "microbleednet"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "natsort>=8.4.0",
    "nibabel>=5.4.2",
    "numpy>=2.2.6",
    "rich>=14.3.3",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
    "simpleitk>=2.5.4",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "typer>=0.24.1",
]

[project.scripts]
microbleednet = "microbleednet.cli.entrypoint:main"
test = "microbleednet.temp_runner:main"

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"
