class TransformConstants:
    # Frangi filter parameters
    FRANGI_FILTER_SIGMAS = (0.5, 1.2, 0.2)
    FRANGI_FILTER_ALPHA = 0.9
    FRANGI_FILTER_BETA = 20
    FRANGI_FILTER_BLACK_RIDGES = False

    # Vessel inpainting parameters
    VESSEL_INPAINTING_CLUSTERER_N_CLUSTERS = 2
    VESSEL_INPAINTING_CLUSTERER_RANDOM_STATE = 42
    VESSEL_INPAINTING_MINIMUM_VESSEL_ECCENTRICITY = 0.9
    VESSEL_INPAINTING_MAXIMUM_VESSEL_SOLIDITY = 0.5

    # Fast Radial Symmetry Transform parameters
    FRST_RADII = [2, 3, 4, 6]
    FRST_ALPHA = 2
    FRST_FACTOR_STD = 0.1
    FRST_BRIGHT = True
    FRST_DARK = False

    # Augmentation parameters
    AUGMENTATION_TRANSLATION_OFFSET_RANGE = (-15, 15) # voxels
    AUGMENTATION_NOISE_VARIANCE_RANGE = (0.01, 0.04)
    AUGMENTATION_BLUR_SIGMA_RANGE = (0.1, 0.2) # voxels