import numpy as np

VERSION_OUTPUT_TEMPLATE = "microbleednet version: [bold green]{version}[/bold green]"
PATTERN_VALIDATION_ERROR_TEMPLATE = "Pattern must include '{string}'. Current pattern: '{pattern}'"

NII_EXTENSION = ".nii"

FRANGI_FILTER_SIGMAS = (0.5, 1.2, 0.2)
FRANGI_FILTER_ALPHA = 0.9
FRANGI_FILTER_BETA = 20
FRANGI_FILTER_BLACK_RIDGES = True

VESSEL_INPAINTING_CLUSTERER_N_CLUSTERS = 2
VESSEL_INPAINTING_CLUSTERER_RANDOM_STATE = 42
VESSEL_INPAINTING_MINIMUM_VESSEL_ECCENTRICITY = 0.9
VESSEL_INPAINTING_MAXIMUM_VESSEL_SOLIDITY = 0.5

FRST_RADII = [2, 3]
FRST_ALPHA = 2
FRST_FACTOR_STD = 0.1
FRST_BRIGHT = False
FRST_DARK = True