dataset_dir = "/mnt/a4ef64ea-1b6b-4423-b1d2-4794d2e97289/gouri/microbleed-data/datasets/non_mIP"
input_dir = "/mnt/a4ef64ea-1b6b-4423-b1d2-4794d2e97289/gouri/microbleed-data/raw-data/Rob_Data/images"
volume_pattern = "{subject_id}_brain_restore.nii.gz"
mask_dir = "/mnt/a4ef64ea-1b6b-4423-b1d2-4794d2e97289/gouri/microbleed-data/raw-data/Rob_Data/masks"
mask_pattern = "{subject_id}_CMB.nii.gz"
source_id = "Rob_Data"
modality = "T2*-GRE"